server:
  port: 8080
  servlet:
    context-path: /springboot
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    format:
      date-time: yyyy-MM-dd
  thymeleaf:
    cache: false
  #决定采用哪个环境的配置
  profiles:
    active: dev
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml